import type { Metadata } from "next";
import { PublicShell } from "@/components/public-shell";

export const metadata: Metadata = { title: "Оставить отзыв", robots: { index: false, follow: true } };

export default async function NewReviewPage({ searchParams }: { searchParams: Promise<{ booking?: string }> }) {
  const { booking = "" } = await searchParams;
  return <PublicShell><section className="page-hero"><div className="container"><div className="breadcrumbs">Главная / Отзывы / Новый отзыв</div><h1 className="page-title">Расскажите о поездке</h1><p className="page-intro">Ваш отзыв помогает нам становиться точнее, а будущим гостям — выбрать подходящий отдых.</p></div></section><section className="section"><div className="container" style={{ maxWidth: 760 }}><form className="form-card form-stack" action="/api/reviews" method="post"><div className="form-grid"><div className="field"><label htmlFor="name">Имя</label><input id="name" name="name" required /></div><div className="field"><label htmlFor="booking">Номер бронирования</label><input id="booking" name="bookingNumber" defaultValue={booking} required /></div></div><div className="field"><label htmlFor="email">Email из бронирования</label><input id="email" name="email" type="email" required /></div><div className="field"><label htmlFor="rating">Оценка</label><select id="rating" name="rating" defaultValue="5"><option value="5">5 — превосходно</option><option value="4">4 — хорошо</option><option value="3">3 — нормально</option><option value="2">2 — есть замечания</option><option value="1">1 — плохо</option></select></div><div className="field"><label htmlFor="text">Ваш отзыв</label><textarea id="text" name="text" minLength={20} maxLength={2000} required /></div><label style={{ display: "flex", gap: 8 }}><input type="checkbox" required /> Согласен на публикацию отзыва</label><button className="button button-primary" type="submit">Отправить отзыв</button></form></div></section></PublicShell>;
}
